# Copy this file to config/secrets.toml and fill in your credentials
# DO NOT COMMIT secrets.toml to git.
[angel_one]
api_key = "YOUR_SMARTAPI_KEY"
client_code = "YOUR_CLIENT_CODE"
password = "YOUR_PASSWORD"
totp_secret = "YOUR_TOTP_SECRET"  # for 2FA TOTP; store safely

[run]
exchange = "NSE"
universe_csv = "data/symbols.csv"    # put your NSE symbols here (SYMBOL column)
capital = 500000                     # total deployable capital (₹)
risk_per_trade = 0.005               # 0.5% per trade

[scan]
# Intraday scan window
intraday_interval = "FIVE_MINUTE"    # Angel One candle interval name
intraday_lookback_minutes = 2_000
intraday_top_n = 8

# Swing scan window (EOD/daily)
swing_interval = "ONE_DAY"
swing_lookback_days = 400
swing_top_n = 10

[filters]
min_price = 50
max_price = 5000
min_avg_volume = 100000

[strategy]
# EMA crossover defaults
fast = 12
slow = 26
atr_period = 14
atr_mult = 2.0

[llm]
enabled = false
provider = "openai"                  # "openai" or "hf"
api_key_env = "OPENAI_API_KEY"       # or HF_API_TOKEN
model = "gpt-4o-mini"                # or a HF model id
temperature = 0.2
max_symbols = 10



# --- Added trading controls ---
[run]
capital = 500000
reserved_ratio = 0.20        # 20% capital reserved (not used for trading)
risk_per_trade = 0.005       # fraction of TOTAL capital as risk per trade (0.005 = 0.5%)

[scan]
intraday_intervals = ["FIVE_MINUTE", "FIFTEEN_MINUTE"]   # candidate intraday intervals to test
intraday_vol_threshold_pct = 0.35   # ATR% threshold (0.35%) to prefer 5-min over 15-min

[strategy]
rr = 2.0                  # default reward:risk ratio for target
min_stop_abs = 0.5        # minimum stop distance in ₹ (useful for very low priced stocks)
